services:
  metadb:
    image: postgres:16
    container_name: metadb
    environment:
      POSTGRES_USER: mbuser
      POSTGRES_PASSWORD: mbpass
      POSTGRES_DB: airlines
    ports:
      - "5432:5432"
    volumes:
      - metadb_data:/var/lib/postgresql/data
      - ./data:/csv                  # put the airline CSV here

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    depends_on: [metadb]
    ports:
      - "3000:3000"
    environment:
      # store Metabase metadata in Postgres (so it persists)
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: mbuser
      MB_DB_PASS: mbpass
      MB_DB_HOST: metadb

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    depends_on: [metadb]
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

volumes:
  metadb_data:
